### ISSUE TITLE
Question about FFN

### ISSUE THREAD

**Issue by 3bobo** [594422814/TransformerTrack#5]
Thanks for your work! I noticed that in the paper, you claimed that  "To achieve a good balance of speed and performance, we slim the classic transformer by omitting the fully-connected feed-forward layers and maintaining the lightweight single-head attention", and it seemed that you also do not use the FFN layer in your code. I'm wondering how about the performance regardless of speed if you use the classic transformer including FFN ？

**Comment by 594422814** [comment]
The proposed method aims to propagate features or masks. Cross-attention plays the key role, which establishes the pixel-to-pixel correspondence.  We observe that FFN does not have an obvious influence on performance.  We also tried to use multiple attention heads.  Since our approach propagates masks, we construct multiple parallel cross-attention blocks and average their output masks as the final mask. For feature propagation, we concatenate the values from multiple heads and use 1*1 conv to reduce the embedding dimension. This multi-head design slightly improves the accuracy, about 0.5% on some testing datasets (such as GOT10K).

**Comment by 3bobo** [comment]
Thanks for your reply! I got your points.
